#!/usr/bin/env python

#import web
import sqlite3 as sql
from datetime import datetime
import cgi
import cgitb; cgitb.enable()  # for troubleshooting

fmt = '%Y-%m-%d %H:%M:%S'
timestamp = datetime.now().strftime(fmt)
path_sensors = '/home/pi/thermo-dev/'
path_www = '/home/pi/www/'

if __name__ == "__main__":
    #    app = web.application(urls, globals())
#    app.run()

    try:
        db_filename = path_sensors + './data/tempResearch_' + datetime.now().strftime('%Y') + '.db'
        conn = sql.connect(db_filename)
        with conn:
            c = conn.cursor()
            c.execute( '''SELECT * FROM power order by rowid desc limit 1;''' )
            data_power = c.fetchone()

            c.execute( '''SELECT * FROM sensors order by rowid desc limit 1;''' )
            data_sensors = c.fetchone()

        conn.close()

    except sql.Error, e:
        
        print 'Error %s:' % e.args[0]
        sys.exit(1)

    try:
        db_filename = path_www + './data/parameters.db'
        conn = sql.connect(db_filename)
        with conn:
            c = conn.cursor()
            c.execute( '''SELECT * FROM temperatures order by rowid desc limit 1;''' )
            data_temps = c.fetchone()
#            c.execute( '''SELECT * FROM temperatures order by rowid desc limit 1;''' )

        conn.close()

    except sql.Error, e:
        
        print 'Error %s:' % e.args[0]
        sys.exit(1)


# Read form
    form = cgi.FieldStorage()
    input = {}
    for key in form.keys():
        input[key] = form[key].value

    print "Content-type: text/html\r\n" #debug
    print input #debug

    if "form_type" in input:

        if input["form_type"] == "toggle_th":
            if 'toggle_manual' in input:
                toggle_manual = 'm'
                if 'toggle_th1' in input:
                    manual_th1 = 0
                else:
                    manual_th1 = 1
                if 'toggle_th2' in input:
                    manual_th2 = 0
                else:
                    manual_th2 = 1
            else:
                toggle_manual = 'a'

            db_filename = path_www + './data/parameters.db'
            conn = sql.connect(db_filename)
            with conn:
                c = conn.cursor()
                c.execute( '''INSERT INTO toggles VALUES
                    (?,?,?,?)''', (toggle_manual, manual_th1, manual_th2, timestamp) )

            conn.close()

        elif input['form_type'] == 'change_temperatures':
            pass

#            conn = sql.connect(db_filename)
#            with conn:
#                c = conn.cursor()
#                c.execute( '''INSERT INTO toggles VALUES
#                    (?, ?, ?, ?)''', ( timestamp, 
            

#    T1 = data_sensors[2]
#    T2 = data_sensors[3]
#    T3 = data_sensors[4]
#    T4 = data_sensors[5]
#    Tfuse1 = data_sensors[6]
#    Tfuse2 = data_sensors[7]
#    Tfuse3 = data_sensors[8]
    Vin_state = data_sensors[9]
    th1_state = data_sensors[10]
    th2_state = data_sensors[11]

    print "Content-type: text/html\r\n"
    print input #debug

    print """
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EL"
     "http://www.w3.org/TR/xhtml1/DTD xhml1-strict.dtd">
    <html xmlns='http://www.w3.org/1999/html' lang='en' xml:lang='en'>
    
    <head>
     <link rel="stylesheet" type="text/css" href="./css/styles.css" />
     <script type="text/javascript" src="./js/jquery-3.2.0.min.js"></script>
     
     <script type="text/javascript">
      $(document).ready(function() {

          $("#testing").text("hahaha")

          $(".toggle_boilers").hide()

        $("#toggle_manual").on("click", function() {
          console.log( $( "input[name='toggle_th1']" ).val() )
          $(".toggle_boilers").show()
        })
      })
     </script>
       
    </head>
    <body>
    """

    print """<p id="testing">""", data_sensors[0], "</p>" #debug
    print """
     <p style="color:%s">Power is %s</p>
    """ % ( ('green', 'grey')[Vin_state], ('on', 'off')[Vin_state] )

    color_state = ('red', 'blue')
    print """
    <form method="get" action="index.py">
     <input type="hidden" name="form_type" value="toggle_th"/>
     <table>
      <tr>
       <td>Manual</td>
       <td>
        <label class="switch">
          <input type="checkbox" id="toggle_manual" name="toggle_manual">
          <div class="slider"></div>
        </label>
       </td>
        
      <tr>
       <td style="color:%s">Boiler 1</td>
       <td>
        <label class="switch toggle_boilers">
          <input type="checkbox" value="1" name="toggle_th1">
          <div class="slider round"></div>
        </label>
       </td>
      </tr>
      <tr>
       <td style="color:%s">Boiler 2</td>
       <td>
        <label class="switch toggle_boilers">
          <input type="checkbox" value="1" name="toggle_th2">
          <div class="slider round"></div>
        </label>
       </td>
      </tr>
     </table>
     <button type="submit">Submit!</button>
    </form>
    """ % ( color_state[th1_state], color_state[th2_state] ) 

    print """<table border="1"><tr>"""
    for i in ('T1', 'T2', 'T3', 'T4', 'Tfuse1', 'Tfuse2', 'Tfuse3'):
        print "<td><h3>%s</h3></td>" % i
    print "</tr>"
    print "<tr>"
    for i in range( len(data_sensors) )[slice(2, 9)]:
        print "<td>%s</td>" % data_sensors[i]
    print """</tr></table><br/>""" 

    print data_power[0]
    print """<table border="1"><tr>"""
    for i in ('L1', 'L2', 'L3'):
        print """<td><h3>%s</h3></td>""" % i
    print "</tr><tr>"
    for i in range( len(data_power) )[slice(1,4)]:
        print """<td>%s</td>""" % data_power[i] 
    print """</tr></table><br/>"""


    print """
     <p>%s</p>
     <form method="get" action="index.py">
     <table border="1"><tr>
    """ % data_temps[-1] #timestamp
    hours = ('00', '01', '02', '03', '04', '05', '06', '07', '08', '09', 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23)
    for i in hours:#range( len(data_temps) )[:-1]: #[slice( 1, len(data_temps) )]:
        print """<td>%s:</td>""" % i
    print """</tr><tr>"""
    for i in hours: #range( len(data_temps) )[slice( 1, len(data_temps) )]:
        print """<td><input type="text" name="H_%s" value="%s" style="width:20px;"/></td>""" % ( i, data_temps[int(i)] )
    print """
     </tr></table>
     <input type ="hidden" name="form_type" value="change_temperatures"/>
     <button type="submit">Submit!</button>
     </form>
    """

    print [i for i in data_temps]
    print '</p>'

    print '</body>'
